---
apiVersion: v1
kind: ConfigMap
metadata:
  name: efs-provisioner
  namespace: efs-provisioner
data:
  file.system.id: fs-621100e3
  aws.region: us-east-1
  provisioner.name: openshift.org/aws-efs 
